version: '3.1'

services:
  app:
    networks:
      - proxy
      - default
    environment:
      ENV: 'demo,test-data,https'
      SESSION_KEY: 'demo-session-key'
      SMTP_HOST: codeborne.com
      PROXY_AUTH_USER: app
      PROXY_AUTH_PASSWORD: app
    volumes:
      - logs:/app/logs

volumes:
  logs:

networks:
  proxy:
    external: true
